### ISSUE TITLE
[BUG] ValueError: not enough values to unpack (expected 4, got 2)

### ISSUE THREAD

**Issue by goldyfruit** [NeonGeckoCom/skill-caffeinewiz#58]
### Description

When asking `'how much caffeine in pepsi` the skill is not able to handle the request.

```
2023-03-29 21:52:05.225 - skills - mycroft.skills.intent_service:_normalize_all_utterances:61 - DEBUG - Utterances: [('how much caffeine in pepsi',)]
2023-03-29 21:52:05.227 - skills - mycroft.skills.intent_services.padatious_service:_match_level:87 - DEBUG - Padatious Matching confidence > 0.95
2023-03-29 21:52:05.237 - skills - mycroft.skills.intent_services.commonqa_service:handle_question:119 - INFO - Searching for how much caffeine in pepsi
2023-03-29 21:52:05.281 - skills - skill-caffeinewiz_neongeckocom:CQS_match_query_phrase:206 - INFO - <mycroft_bus_client.message.Message object at 0x7f1ff46f0390>
2023-03-29 21:52:05.285 - skills - skill-caffeinewiz_neongeckocom:_clean_drink_name:499 - INFO - pepsi cola
2023-03-29 21:52:05.286 - skills - skill-caffeinewiz_neongeckocom:_generate_drink_dialog:519 - DEBUG - [['pepsi cola', '12', '38'], ['pepsi', '12', '150', '38']]
2023-03-29 21:52:05.287 - skills - skill-caffeinewiz_neongeckocom:_generate_drink_dialog:538 - DEBUG - ['pepsi cola']
2023-03-29 21:52:05.288 - skills - skill-caffeinewiz_neongeckocom:_generate_drink_dialog:539 - DEBUG - [['pepsi cola', '12', '38']]
2023-03-29 21:52:05.289 - skills - neon_utils.configuration_utils:get_config_dir:658 - DEBUG - /home/ovos/.config/neon
2023-03-29 21:52:05.293 - skills - ovos_config.models:load_local:96 - DEBUG - Configuration /home/ovos/.config/mycroft/mycroft.conf loaded
2023-03-29 21:52:05.294 - skills - neon_utils.configuration_utils:get_user_config_from_mycroft_conf:813 - DEBUG - Initializing mycroft config at /home/ovos/.config/mycroft/mycroft.conf
2023-03-29 21:52:05.294 - skills - neon_utils.configuration_utils:get_user_config_from_mycroft_conf:837 - WARNING - No location in config: /home/ovos/.config/mycroft/mycroft.conf
2023-03-29 21:52:05.295 - skills - skill-caffeinewiz_neongeckocom:_generate_drink_dialog:551 - INFO - pepsi cola | 38.0 | 12.0 | word_ounces
2023-03-29 21:52:05.298 - skills - skill-caffeinewiz_neongeckocom:CQS_match_query_phrase:224 - DEBUG - pepsi cola
2023-03-29 21:52:05.300 - skills - skill-caffeinewiz_neongeckocom:CQS_match_query_phrase:250 - INFO - results=[['pepsi cola', '12', '38'], ['pepsi', '12', '150', '38']]
2023-03-29 21:52:05.341 - skills - mycroft.skills.intent_services.commonqa_service:handle_query_response:153 - INFO - Answer from skill-caffeinewiz.neongeckocom
2023-03-29 21:52:05.675 - skills - ovos_workshop.skills.base:_on_event_error:1230 - ERROR - not enough values to unpack (expected 4, got 2)
Traceback (most recent call last):
  File "/home/ovos/.venv/lib/python3.11/site-packages/ovos_utils/messagebus.py", line 351, in wrapper
    handler(message)
  File "/home/ovos/.venv/lib/python3.11/site-packages/mycroft/skills/common_query_skill.py", line 106, in __handle_question_query
    result = self.CQS_match_query_phrase(search_phrase)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/skill_ovos_wikipedia/__init__.py", line 94, in CQS_match_query_phrase
    summary = self.ask_the_wiki(utt)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/skill_ovos_wikipedia/__init__.py", line 112, in ask_the_wiki
    self.results = self.wiki.long_answer(query, lang=self.lang)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/neon_solvers/solver.py", line 195, in long_answer
    steps = self.get_expanded_answer(query, context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/neon_solver_wikipedia_plugin/__init__.py", line 129, in get_expanded_answer
    data = self.get_data(query, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/neon_solver_wikipedia_plugin/__init__.py", line 95, in get_data
    "short_answer": wikipedia_for_humans.tldr(query, lang=lang),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/wikipedia_for_humans/__init__.py", line 397, in tldr
    return short_answer(query, lang)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/wikipedia_for_humans/__init__.py", line 356, in short_answer
    answer = summary(query, lang)
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/wikipedia_for_humans/__init__.py", line 346, in summary
    results = search_wikipedia(query, limit=1)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ovos/.venv/lib/python3.11/site-packages/wikipedia_for_humans/__init__.py", line 130, in search_wikipedia
    _, results, _, urls = r.json()
    ^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 4, got 2)
```

### Steps to Reproduce

Ask `'how much caffeine in pepsi`

**Comment by NeonDaniel** [comment]
It looks like the bug came from wikipedia, so this might belong there or in Common Query handling in ovos-core?

**Comment by NeonDaniel** [comment]
Unrelated to this skill
